'use client';

/**
 * Editing one rule.
 *
 * The shape on screen is the shape of the data: a WHEN row, a stack of IF
 * rows, and a stack of THEN rows. Every control is a plain select or number
 * box, so a rule can be built without knowing that any of this is JSON, and
 * the sentence at the top of the card is generated by the same describer the
 * log uses — if the card and the log ever disagree, one of them is lying.
 */

import * as React from 'react';
import { Button, NumberBox, Select, cn } from '@/components/ui/primitives';
import { PROP_LABELS } from '@/lib/engine/odds';
import type { AtsKind, BetKind, DieFace, PointNumber, PropKind } from '@/lib/engine/types';
import {
  BET_KIND_LABELS,
  ONCE_LABELS,
  TRIGGER_HINTS,
  TRIGGER_LABELS,
  describeAction,
  describeCondition,
  describeRule,
} from '@/lib/strategy/describe';
import {
  COMPARISONS,
  type Action,
  type ActionKind,
  type Amount,
  type AmountMode,
  type BetTarget,
  type Comparison,
  type Condition,
  type ConditionKind,
  type NumberRef,
  type OddsTarget,
  type OnceScope,
  type StrategyRule,
  type TakeDownTarget,
  type Trigger,
} from '@/lib/strategy/types';

/* ------------------------------------------------------------------ *
 * Option lists
 * ------------------------------------------------------------------ */

const TRIGGER_OPTIONS = (Object.keys(TRIGGER_LABELS) as Trigger[]).map((value) => ({
  value,
  label: TRIGGER_LABELS[value],
}));

const ONCE_OPTIONS = (Object.keys(ONCE_LABELS) as OnceScope[]).map((value) => ({
  value,
  label: ONCE_LABELS[value],
}));

const BET_KINDS: BetKind[] = [
  'PASS',
  'DONT_PASS',
  'COME',
  'DONT_COME',
  'PLACE',
  'BUY',
  'LAY',
  'HARDWAY',
  'FIELD',
  'PROP',
  'HOP',
  'BIG',
  'FIRE',
  'ATS',
];

const BET_KIND_OPTIONS = BET_KINDS.map((value) => ({ value, label: BET_KIND_LABELS[value] }));

const NUMBER_REF_OPTIONS: ReadonlyArray<{ value: string; label: string }> = [
  { value: 'POINT', label: 'the point' },
  { value: 'HIT', label: 'the number that hit' },
  { value: '4', label: 'the 4' },
  { value: '5', label: 'the 5' },
  { value: '6', label: 'the 6' },
  { value: '8', label: 'the 8' },
  { value: '9', label: 'the 9' },
  { value: '10', label: 'the 10' },
  { value: 'INSIDE', label: 'inside (5 6 8 9)' },
  { value: 'OUTSIDE', label: 'outside (4 5 9 10)' },
  { value: 'ACROSS', label: 'across (all six)' },
];

const PROP_OPTIONS = (Object.keys(PROP_LABELS) as PropKind[]).map((value) => ({
  value,
  label: PROP_LABELS[value],
}));

const ATS_OPTIONS: ReadonlyArray<{ value: AtsKind; label: string }> = [
  { value: 'ALL', label: 'All' },
  { value: 'TALL', label: 'Tall' },
  { value: 'SMALL', label: 'Small' },
];

const ODDS_TARGET_OPTIONS: ReadonlyArray<{ value: OddsTarget; label: string }> = [
  { value: 'ALL', label: 'every line bet' },
  { value: 'PASS', label: 'the pass line' },
  { value: 'DONT_PASS', label: "don't pass" },
  { value: 'COME', label: 'come bets' },
  { value: 'DONT_COME', label: "don't come bets" },
];

const CONDITION_OPTIONS: ReadonlyArray<{ value: ConditionKind; label: string }> = [
  { value: 'HAS_BET', label: 'a bet I hold' },
  { value: 'BET_AMOUNT', label: 'what is on a spot' },
  { value: 'BET_COUNT', label: 'how many bets of a kind' },
  { value: 'POINT_IS', label: 'the point' },
  { value: 'HIT_IS', label: 'the number that hit' },
  { value: 'HITS_ON', label: 'hits on a number' },
  { value: 'LAST_TOTAL', label: 'the last roll' },
  { value: 'ROLLS_THIS_HAND', label: 'rolls this hand' },
  { value: 'POINTS_THIS_HAND', label: 'points made this hand' },
  { value: 'BANKROLL', label: 'my rack' },
  { value: 'AT_RISK', label: 'what I have on the felt' },
  { value: 'SESSION_NET', label: 'my session' },
  { value: 'HAND_NET', label: 'this hand' },
  { value: 'IM_SHOOTING', label: 'who is shooting' },
];

const ACTION_OPTIONS: ReadonlyArray<{ value: ActionKind; label: string }> = [
  { value: 'BET', label: 'bet' },
  { value: 'ODDS', label: 'odds' },
  { value: 'PRESS', label: 'press' },
  { value: 'REGRESS', label: 'regress' },
  { value: 'TAKE_DOWN', label: 'take down' },
  { value: 'WORKING', label: 'turn on / off' },
  { value: 'STOP', label: 'stop betting' },
];

const COMPARISON_OPTIONS = COMPARISONS.map((c) => ({ value: c.value, label: c.label }));

const BOX_NUMBERS: PointNumber[] = [4, 5, 6, 8, 9, 10];

/* Which amount modes each kind of action offers, and which need a figure. */

const AMOUNT_LABELS: Record<AmountMode, string> = {
  UNITS: 'units',
  FIXED: 'dollars',
  TABLE_MIN: 'the table minimum',
  PCT_BANKROLL: '% of my rack',
  DOUBLE: 'double it',
  WIN: 'what it just won',
  HALF_WIN: 'half what it won',
  TO: 'up to',
  MAX: 'the maximum',
  MULTIPLE: 'x the flat bet',
};

const MODES_FOR: Record<'BET' | 'ODDS' | 'PRESS' | 'REGRESS', AmountMode[]> = {
  BET: ['UNITS', 'FIXED', 'TABLE_MIN', 'PCT_BANKROLL'],
  ODDS: ['MAX', 'MULTIPLE', 'UNITS', 'FIXED'],
  PRESS: ['UNITS', 'FIXED', 'DOUBLE', 'WIN', 'HALF_WIN', 'TO'],
  REGRESS: ['UNITS', 'FIXED', 'TO'],
};

const MODE_NEEDS_VALUE: ReadonlySet<AmountMode> = new Set<AmountMode>([
  'UNITS',
  'FIXED',
  'PCT_BANKROLL',
  'TO',
  'MULTIPLE',
]);

/** Bet kinds that sit on a box number and so need a number reference. */
const KIND_TAKES_NUMBER: ReadonlySet<BetKind> = new Set<BetKind>([
  'PLACE',
  'BUY',
  'LAY',
  'HARDWAY',
  'BIG',
]);

/* ------------------------------------------------------------------ *
 * Defaults when a row changes type
 * ------------------------------------------------------------------ */

function defaultCondition(kind: ConditionKind): Condition {
  switch (kind) {
    case 'POINT_IS':
      return { t: 'POINT_IS', numbers: [] };
    case 'HIT_IS':
      return { t: 'HIT_IS', numbers: [] };
    case 'LAST_TOTAL':
      return { t: 'LAST_TOTAL', op: 'EQ', value: 7 };
    case 'HAS_BET':
      return { t: 'HAS_BET', target: { kind: 'PLACE', number: 6 }, has: false };
    case 'BET_AMOUNT':
      return { t: 'BET_AMOUNT', target: { kind: 'PLACE', number: 'HIT' }, op: 'LT', value: 60 };
    case 'BET_COUNT':
      return { t: 'BET_COUNT', kind: 'COME', op: 'LT', value: 2 };
    case 'BANKROLL':
      return { t: 'BANKROLL', op: 'GTE', value: 100 };
    case 'AT_RISK':
      return { t: 'AT_RISK', op: 'LT', value: 100 };
    case 'SESSION_NET':
      return { t: 'SESSION_NET', op: 'GTE', value: 100 };
    case 'HAND_NET':
      return { t: 'HAND_NET', op: 'GTE', value: 50 };
    case 'ROLLS_THIS_HAND':
      return { t: 'ROLLS_THIS_HAND', op: 'GTE', value: 5 };
    case 'HITS_ON':
      return { t: 'HITS_ON', number: 'HIT', op: 'GTE', value: 2 };
    case 'POINTS_THIS_HAND':
      return { t: 'POINTS_THIS_HAND', op: 'GTE', value: 1 };
    case 'IM_SHOOTING':
      return { t: 'IM_SHOOTING', value: true };
  }
}

function defaultAction(kind: ActionKind): Action {
  switch (kind) {
    case 'BET':
      return { t: 'BET', target: { kind: 'PLACE', number: 6 }, amount: { mode: 'UNITS', value: 1 } };
    case 'ODDS':
      return { t: 'ODDS', on: 'ALL', amount: { mode: 'MAX', value: 0 } };
    case 'PRESS':
      return { t: 'PRESS', number: 'HIT', amount: { mode: 'UNITS', value: 1 } };
    case 'REGRESS':
      return { t: 'REGRESS', number: 'INSIDE', amount: { mode: 'UNITS', value: 1 } };
    case 'TAKE_DOWN':
      return { t: 'TAKE_DOWN', target: { all: true } };
    case 'WORKING':
      return { t: 'WORKING', number: 'ACROSS', on: true };
    case 'STOP':
      return { t: 'STOP', reason: 'that is enough for today' };
  }
}

/* ------------------------------------------------------------------ *
 * Shared little editors
 * ------------------------------------------------------------------ */

function refToValue(ref: NumberRef): string {
  return String(ref);
}

function valueToRef(value: string): NumberRef {
  const n = Number(value);
  return Number.isNaN(n) ? (value as NumberRef) : (n as NumberRef);
}

function NumberRefSelect({
  value,
  onChange,
  title,
}: {
  value: NumberRef;
  onChange: (v: NumberRef) => void;
  title?: string;
}) {
  return (
    <Select
      value={refToValue(value)}
      options={NUMBER_REF_OPTIONS}
      onChange={(v) => onChange(valueToRef(v))}
      title={title}
      ariaLabel="Which number"
    />
  );
}

/** The 4-5-6-8-9-10 toggle strip used by "the point is…" and "the hit is…". */
function BoxNumberPicker({
  value,
  onChange,
}: {
  value: PointNumber[];
  onChange: (v: PointNumber[]) => void;
}) {
  return (
    <span className="inline-flex items-center gap-1">
      {BOX_NUMBERS.map((n) => {
        const on = value.includes(n);
        return (
          <button
            key={n}
            type="button"
            aria-pressed={on}
            onClick={() => onChange(on ? value.filter((x) => x !== n) : [...value, n].sort((a, b) => a - b))}
            className={cn(
              'tabular h-7 w-7 rounded border text-[11px] font-semibold transition-colors',
              on
                ? 'border-brass-500/60 bg-brass-500/25 text-brass-200'
                : 'border-white/10 bg-pit-850 text-pit-400 hover:text-pit-100',
            )}
          >
            {n}
          </button>
        );
      })}
      {value.length === 0 ? <span className="text-[10px] text-pit-400">any</span> : null}
    </span>
  );
}

/** Bet kind, plus whichever extra control that kind needs. */
function TargetEditor({
  value,
  onChange,
}: {
  value: BetTarget;
  onChange: (v: BetTarget) => void;
}) {
  const takesNumber = KIND_TAKES_NUMBER.has(value.kind);
  const isGroup =
    typeof value.number === 'string' && ['INSIDE', 'OUTSIDE', 'ACROSS'].includes(value.number);

  return (
    <span className="inline-flex flex-wrap items-center gap-1">
      <Select
        value={value.kind}
        options={BET_KIND_OPTIONS}
        ariaLabel="Which bet"
        onChange={(kind) => {
          const next: BetTarget = { kind };
          if (KIND_TAKES_NUMBER.has(kind)) next.number = value.number ?? 6;
          if (kind === 'PROP') next.prop = value.prop ?? 'ANY_CRAPS';
          if (kind === 'ATS') next.ats = value.ats ?? 'ALL';
          if (kind === 'HOP') next.hop = value.hop ?? [3, 4];
          onChange(next);
        }}
      />

      {takesNumber ? (
        <NumberRefSelect
          value={value.number ?? 6}
          onChange={(number) => onChange({ ...value, number })}
        />
      ) : null}

      {takesNumber && isGroup ? (
        <label className="inline-flex items-center gap-1 text-[10px] text-pit-400">
          <input
            type="checkbox"
            checked={value.exceptPoint ?? false}
            onChange={(e) => onChange({ ...value, exceptPoint: e.target.checked })}
            className="accent-brass-500"
          />
          except the point
        </label>
      ) : null}

      {value.kind === 'PROP' ? (
        <Select
          value={value.prop ?? 'ANY_CRAPS'}
          options={PROP_OPTIONS}
          ariaLabel="Which proposition"
          onChange={(prop) => onChange({ ...value, prop })}
        />
      ) : null}

      {value.kind === 'ATS' ? (
        <Select
          value={value.ats ?? 'ALL'}
          options={ATS_OPTIONS}
          ariaLabel="Which side bet"
          onChange={(ats) => onChange({ ...value, ats })}
        />
      ) : null}

      {value.kind === 'HOP' ? (
        <span className="inline-flex items-center gap-1">
          {([0, 1] as const).map((i) => (
            <Select
              key={i}
              value={String(value.hop?.[i] ?? (i === 0 ? 3 : 4))}
              options={[1, 2, 3, 4, 5, 6].map((f) => ({ value: String(f), label: String(f) }))}
              ariaLabel={`Die ${i + 1}`}
              className="w-12"
              onChange={(v) => {
                const hop: [DieFace, DieFace] = [...(value.hop ?? [3, 4])] as [DieFace, DieFace];
                hop[i] = Number(v) as DieFace;
                onChange({ ...value, hop });
              }}
            />
          ))}
        </span>
      ) : null}
    </span>
  );
}

function AmountEditor({
  value,
  onChange,
  context,
}: {
  value: Amount;
  onChange: (v: Amount) => void;
  context: keyof typeof MODES_FOR;
}) {
  const modes = MODES_FOR[context];
  const needsValue = MODE_NEEDS_VALUE.has(value.mode);
  // "up to $30" and "2 x the flat bet" read with the figure on opposite sides.
  const valueFirst = value.mode === 'UNITS' || value.mode === 'PCT_BANKROLL' || value.mode === 'MULTIPLE';

  const box = needsValue ? (
    <NumberBox
      value={value.value}
      min={0}
      onChange={(n) => onChange({ ...value, value: n })}
      prefix={value.mode === 'FIXED' || value.mode === 'TO' ? '$' : undefined}
      ariaLabel="How much"
    />
  ) : null;

  return (
    <span className="inline-flex items-center gap-1">
      {valueFirst ? box : null}
      <Select
        value={value.mode}
        options={modes.map((m) => ({ value: m, label: AMOUNT_LABELS[m] }))}
        ariaLabel="Amount"
        onChange={(mode) => onChange({ mode, value: value.value })}
      />
      {valueFirst ? null : box}
    </span>
  );
}

function CompareRow({
  op,
  value,
  onChange,
  prefix,
  min = 0,
}: {
  op: Comparison;
  value: number;
  onChange: (op: Comparison, value: number) => void;
  prefix?: string;
  min?: number;
}) {
  return (
    <>
      <Select
        value={op}
        options={COMPARISON_OPTIONS}
        ariaLabel="Comparison"
        onChange={(next) => onChange(next, value)}
      />
      <NumberBox
        value={value}
        min={min}
        prefix={prefix}
        onChange={(n) => onChange(op, n)}
        ariaLabel="Value"
      />
    </>
  );
}

/* ------------------------------------------------------------------ *
 * Condition rows
 * ------------------------------------------------------------------ */

function ConditionRow({
  value,
  onChange,
  onRemove,
}: {
  value: Condition;
  onChange: (v: Condition) => void;
  onRemove: () => void;
}) {
  return (
    <div className="flex flex-wrap items-center gap-1 rounded-md border border-white/[0.06] bg-pit-900/50 px-2 py-1.5">
      <Select
        value={value.t}
        options={CONDITION_OPTIONS}
        ariaLabel="Condition"
        className="min-w-[9.5rem]"
        onChange={(t) => onChange(defaultCondition(t))}
      />

      {value.t === 'POINT_IS' || value.t === 'HIT_IS' ? (
        <>
          <span className="text-[11px] text-pit-400">is</span>
          <BoxNumberPicker
            value={value.numbers}
            onChange={(numbers) => onChange({ ...value, numbers })}
          />
        </>
      ) : null}

      {value.t === 'HAS_BET' ? (
        <>
          <Select
            value={value.has ? 'yes' : 'no'}
            options={[
              { value: 'no', label: 'is not there' },
              { value: 'yes', label: 'is there' },
            ]}
            ariaLabel="Held or not"
            onChange={(v) => onChange({ ...value, has: v === 'yes' })}
          />
          <TargetEditor value={value.target} onChange={(target) => onChange({ ...value, target })} />
        </>
      ) : null}

      {value.t === 'BET_AMOUNT' ? (
        <>
          <TargetEditor value={value.target} onChange={(target) => onChange({ ...value, target })} />
          <CompareRow
            op={value.op}
            value={value.value}
            prefix="$"
            onChange={(op, v) => onChange({ ...value, op, value: v })}
          />
        </>
      ) : null}

      {value.t === 'BET_COUNT' ? (
        <>
          <Select
            value={value.kind}
            options={BET_KIND_OPTIONS}
            ariaLabel="Which bet"
            onChange={(kind) => onChange({ ...value, kind })}
          />
          <CompareRow
            op={value.op}
            value={value.value}
            onChange={(op, v) => onChange({ ...value, op, value: v })}
          />
        </>
      ) : null}

      {value.t === 'HITS_ON' ? (
        <>
          <NumberRefSelect
            value={value.number}
            onChange={(number) => onChange({ ...value, number })}
          />
          <CompareRow
            op={value.op}
            value={value.value}
            onChange={(op, v) => onChange({ ...value, op, value: v })}
          />
        </>
      ) : null}

      {value.t === 'LAST_TOTAL' ||
      value.t === 'ROLLS_THIS_HAND' ||
      value.t === 'POINTS_THIS_HAND' ? (
        <CompareRow
          op={value.op}
          value={value.value}
          onChange={(op, v) => onChange({ ...value, op, value: v })}
        />
      ) : null}

      {value.t === 'BANKROLL' ||
      value.t === 'AT_RISK' ||
      value.t === 'SESSION_NET' ||
      value.t === 'HAND_NET' ? (
        <CompareRow
          op={value.op}
          value={value.value}
          prefix="$"
          min={value.t === 'SESSION_NET' || value.t === 'HAND_NET' ? -100_000 : 0}
          onChange={(op, v) => onChange({ ...value, op, value: v })}
        />
      ) : null}

      {value.t === 'IM_SHOOTING' ? (
        <Select
          value={value.value ? 'me' : 'them'}
          options={[
            { value: 'me', label: 'is me' },
            { value: 'them', label: 'is the other seat' },
          ]}
          ariaLabel="Who is shooting"
          onChange={(v) => onChange({ ...value, value: v === 'me' })}
        />
      ) : null}

      <button
        type="button"
        onClick={onRemove}
        aria-label="Remove condition"
        title="Remove this condition"
        className="ml-auto rounded px-1.5 text-[13px] leading-none text-pit-400 hover:bg-white/5 hover:text-lose"
      >
        ×
      </button>
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * Action rows
 * ------------------------------------------------------------------ */

function ActionRow({
  value,
  onChange,
  onRemove,
}: {
  value: Action;
  onChange: (v: Action) => void;
  onRemove: () => void;
}) {
  return (
    <div className="flex flex-wrap items-center gap-1 rounded-md border border-brass-500/15 bg-brass-500/[0.06] px-2 py-1.5">
      <Select
        value={value.t}
        options={ACTION_OPTIONS}
        ariaLabel="Action"
        className="min-w-[7rem]"
        onChange={(t) => onChange(defaultAction(t))}
      />

      {value.t === 'BET' ? (
        <>
          <TargetEditor value={value.target} onChange={(target) => onChange({ ...value, target })} />
          <span className="text-[11px] text-pit-400">{value.topUp ? 'add' : 'up to'}</span>
          <AmountEditor
            value={value.amount}
            context="BET"
            onChange={(amount) => onChange({ ...value, amount })}
          />
          <label
            className="inline-flex items-center gap-1 text-[10px] text-pit-400"
            title="Off: bring the spot up to this amount. On: add this much on top of whatever is already there."
          >
            <input
              type="checkbox"
              checked={value.topUp ?? false}
              onChange={(e) => onChange({ ...value, topUp: e.target.checked })}
              className="accent-brass-500"
            />
            on top
          </label>
        </>
      ) : null}

      {value.t === 'ODDS' ? (
        <>
          <span className="text-[11px] text-pit-400">behind</span>
          <Select
            value={value.on}
            options={ODDS_TARGET_OPTIONS}
            ariaLabel="Which line bets"
            onChange={(on) => onChange({ ...value, on })}
          />
          <span className="text-[11px] text-pit-400">take</span>
          <AmountEditor
            value={value.amount}
            context="ODDS"
            onChange={(amount) => onChange({ ...value, amount })}
          />
        </>
      ) : null}

      {value.t === 'PRESS' || value.t === 'REGRESS' ? (
        <>
          <NumberRefSelect
            value={value.number}
            onChange={(number) => onChange({ ...value, number })}
          />
          <span className="text-[11px] text-pit-400">{value.t === 'PRESS' ? 'by' : 'to'}</span>
          <AmountEditor
            value={value.amount}
            context={value.t}
            onChange={(amount) => onChange({ ...value, amount })}
          />
        </>
      ) : null}

      {value.t === 'TAKE_DOWN' ? (
        <>
          <Select
            value={value.target.all ? 'all' : 'one'}
            options={[
              { value: 'all', label: 'everything that can come down' },
              { value: 'one', label: 'one spot' },
            ]}
            ariaLabel="What comes down"
            onChange={(v) =>
              onChange({
                ...value,
                target:
                  v === 'all'
                    ? ({ all: true } as TakeDownTarget)
                    : ({ target: value.target.target ?? { kind: 'PLACE', number: 'HIT' } } as TakeDownTarget),
              })
            }
          />
          {!value.target.all ? (
            <TargetEditor
              value={value.target.target ?? { kind: 'PLACE', number: 'HIT' }}
              onChange={(target) => onChange({ ...value, target: { target } })}
            />
          ) : null}
        </>
      ) : null}

      {value.t === 'WORKING' ? (
        <>
          <NumberRefSelect
            value={value.number}
            onChange={(number) => onChange({ ...value, number })}
          />
          <Select
            value={value.on ? 'on' : 'off'}
            options={[
              { value: 'on', label: 'ON' },
              { value: 'off', label: 'OFF' },
            ]}
            ariaLabel="On or off"
            onChange={(v) => onChange({ ...value, on: v === 'on' })}
          />
        </>
      ) : null}

      {value.t === 'STOP' ? (
        <input
          value={value.reason}
          onChange={(e) => onChange({ ...value, reason: e.target.value.slice(0, 40) })}
          placeholder="why"
          aria-label="Reason for stopping"
          className="h-7 flex-1 rounded border border-white/10 bg-pit-850 px-2 text-[11px] text-pit-100"
        />
      ) : null}

      <button
        type="button"
        onClick={onRemove}
        aria-label="Remove action"
        title="Remove this action"
        className="ml-auto rounded px-1.5 text-[13px] leading-none text-pit-400 hover:bg-white/5 hover:text-lose"
      >
        ×
      </button>
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * The card
 * ------------------------------------------------------------------ */

export function RuleCard({
  rule,
  unit,
  index,
  count,
  warnings,
  readOnly,
  onChange,
  onRemove,
  onMove,
}: {
  rule: StrategyRule;
  unit: number;
  index: number;
  count: number;
  warnings: string[];
  readOnly?: boolean;
  onChange: (rule: StrategyRule) => void;
  onRemove: () => void;
  onMove: (delta: number) => void;
}) {
  const [open, setOpen] = React.useState(false);
  const sentence = describeRule(rule, unit);

  const patch = (next: Partial<StrategyRule>) => onChange({ ...rule, ...next });

  if (readOnly) {
    return (
      <li className="rounded-lg border border-white/[0.06] bg-pit-900/40 px-3 py-2">
        <div className="flex items-baseline gap-2">
          <span className="tabular shrink-0 text-[10px] text-pit-400">{index + 1}</span>
          <span className="min-w-0">
            {rule.note ? (
              <span className="block text-xs font-semibold text-pit-100">{rule.note}</span>
            ) : null}
            <span className="block text-[11px] leading-relaxed text-pit-300">{sentence}</span>
          </span>
        </div>
      </li>
    );
  }

  return (
    <li
      className={cn(
        'rounded-lg border bg-pit-900/40 transition-colors',
        warnings.length > 0 ? 'border-amber-400/30' : 'border-white/[0.06]',
        !rule.enabled && 'opacity-50',
      )}
    >
      <div className="flex items-start gap-2 px-2.5 py-2">
        <input
          type="checkbox"
          checked={rule.enabled}
          onChange={(e) => patch({ enabled: e.target.checked })}
          aria-label={`Rule ${index + 1} enabled`}
          title={rule.enabled ? 'Switch this rule off' : 'Switch this rule on'}
          className="mt-0.5 accent-brass-500"
        />

        <button
          type="button"
          onClick={() => setOpen((v) => !v)}
          aria-expanded={open}
          className="min-w-0 flex-1 text-left"
        >
          {rule.note ? (
            <span className="block truncate text-xs font-semibold text-pit-100">{rule.note}</span>
          ) : null}
          <span className="block text-[11px] leading-relaxed text-pit-300">{sentence}</span>
        </button>

        <span className="flex shrink-0 items-center gap-0.5">
          <button
            type="button"
            onClick={() => onMove(-1)}
            disabled={index === 0}
            aria-label="Move rule up"
            title="Rules run top to bottom"
            className="rounded px-1 text-[11px] text-pit-400 hover:bg-white/5 hover:text-pit-100 disabled:opacity-25"
          >
            ↑
          </button>
          <button
            type="button"
            onClick={() => onMove(1)}
            disabled={index === count - 1}
            aria-label="Move rule down"
            title="Rules run top to bottom"
            className="rounded px-1 text-[11px] text-pit-400 hover:bg-white/5 hover:text-pit-100 disabled:opacity-25"
          >
            ↓
          </button>
          <button
            type="button"
            onClick={() => setOpen((v) => !v)}
            aria-label={open ? 'Collapse rule' : 'Edit rule'}
            className="rounded px-1.5 text-[11px] text-pit-400 hover:bg-white/5 hover:text-pit-100"
          >
            {open ? '▴' : '▾'}
          </button>
          <button
            type="button"
            onClick={onRemove}
            aria-label="Delete rule"
            className="rounded px-1.5 text-[13px] leading-none text-pit-400 hover:bg-white/5 hover:text-lose"
          >
            ×
          </button>
        </span>
      </div>

      {warnings.length > 0 ? (
        <ul className="border-t border-amber-400/20 bg-amber-400/[0.06] px-3 py-1.5">
          {warnings.map((w) => (
            <li key={w} className="text-[10px] leading-relaxed text-amber-200/90">
              {w}
            </li>
          ))}
        </ul>
      ) : null}

      {open ? (
        <div className="space-y-2 border-t border-white/[0.06] p-2.5">
          {/* WHEN */}
          <div className="flex flex-wrap items-center gap-2">
            <span className="stat-label w-10 shrink-0">When</span>
            <Select
              value={rule.when}
              options={TRIGGER_OPTIONS}
              ariaLabel="When this rule fires"
              title={TRIGGER_HINTS[rule.when]}
              onChange={(when) => patch({ when })}
            />
            <span className="text-[11px] text-pit-400">and fire</span>
            <Select
              value={rule.once}
              options={ONCE_OPTIONS}
              ariaLabel="How often"
              onChange={(once) => patch({ once })}
            />
          </div>
          <p className="pl-12 text-[10px] leading-relaxed text-pit-400">
            {TRIGGER_HINTS[rule.when]}
          </p>

          {/* IF */}
          <div className="flex items-start gap-2">
            <span className="stat-label mt-1.5 w-10 shrink-0">If</span>
            <div className="min-w-0 flex-1 space-y-1.5">
              {rule.all.map((cond, i) => (
                <ConditionRow
                  key={`${cond.t}-${i}`}
                  value={cond}
                  onChange={(next) =>
                    patch({ all: rule.all.map((c, j) => (i === j ? next : c)) })
                  }
                  onRemove={() => patch({ all: rule.all.filter((_, j) => j !== i) })}
                />
              ))}
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => patch({ all: [...rule.all, defaultCondition('HAS_BET')] })}
                >
                  + Condition
                </Button>
                {rule.all.length === 0 ? (
                  <span className="text-[10px] text-pit-400">
                    No conditions — this rule fires whenever its moment comes round.
                  </span>
                ) : (
                  <span className="text-[10px] text-pit-400">All of these must be true.</span>
                )}
              </div>
            </div>
          </div>

          {/* THEN */}
          <div className="flex items-start gap-2">
            <span className="stat-label mt-1.5 w-10 shrink-0">Then</span>
            <div className="min-w-0 flex-1 space-y-1.5">
              {rule.then.map((action, i) => (
                <ActionRow
                  key={`${action.t}-${i}`}
                  value={action}
                  onChange={(next) =>
                    patch({ then: rule.then.map((a, j) => (i === j ? next : a)) })
                  }
                  onRemove={() => patch({ then: rule.then.filter((_, j) => j !== i) })}
                />
              ))}
              <Button
                size="sm"
                variant="ghost"
                onClick={() => patch({ then: [...rule.then, defaultAction('BET')] })}
              >
                + Action
              </Button>
            </div>
          </div>

          {/* NOTE */}
          <div className="flex items-center gap-2">
            <span className="stat-label w-10 shrink-0">Call</span>
            <input
              value={rule.note ?? ''}
              onChange={(e) => patch({ note: e.target.value.slice(0, 48) })}
              placeholder="What you would say at the table"
              aria-label="Rule name"
              className="h-7 flex-1 rounded border border-white/10 bg-pit-850 px-2 text-[11px] text-pit-100"
            />
          </div>
        </div>
      ) : null}
    </li>
  );
}

/* Re-exported so the workshop can preview a rule without importing describe. */
export { describeAction, describeCondition };
